[specification.trajectory]
path = "BioCarbonTrajectories/ALR_6_650_R.nc"

[specification.platform]
type = "alr1500"
NMEA_coordinates = false
ascent_thresh = 0.05  # m/s
descent_thresh= -0.05  # m/s
near_surface_thresh = 1

[specification.navigation]
latitude = "ALATPT01"
longitude = "ALONPT01"
depth = "ADEPPT01"
pitch = "PTCHPT01"
time = "TIME"
heading = "HEADPT01"
roll = "ROLLPT01"

[specification.sensors.ctd.conservative_temperature]
source_id = "noc-npd-era5/npd-eorca12-era5v1/gn/T1m_4d"
variable_name = "thetao_con"
accuracy = 0.001
resolution = 0.0001
drift_per_month = 0.0002
range = [-5, 42]
percent_errors = false
noise_std = 0.0005

[specification.sensors.ctd.absolute_salinity]
source_id = "noc-npd-era5/npd-eorca12-era5v1/gn/T1m_4d"
variable_name = "so_abs"
accuracy = 0.005
resolution = 0.0001
drift_per_month = 0.0003
range = [0, 42]
percent_errors = false
noise_std = 0.0005

[specification.sensors.ctd.pressure]
source_id = ""
variable_name = "pressure"
accuracy = -999.999
resolution = -999.999
drift_per_month = -999.999
range = [-999.999,-999.999]
percent_errors = false
noise_std = -999.999
