[specification.trajectory]
path = "data/RAPID-mooring/rapid-mooring.nc"

[specification.platform]
type = "glider"
NMEA_coordinates = true
ascent_thresh = 0.05  # m/s
descent_thresh= -0.05  # m/s
near_surface_thresh = 1

[specification.navigation]
latitude = "m_lat"
longitude = "m_lon"
depth = "m_depth"
pitch = "m_pitch"
time = "time"

[specification.sensors.ctd.conservative_temperature]
# source_id = "noc-npd-era5/npd-eorca12-era5v1/gn/T1m_4d"
source_id = "rapid_data/2_RAPID36_1d_gridT_RAPID1_202303-202303.nc"
variable_name = "toce_con"
accuracy = 0.001
resolution = 0.0001
drift_per_month = 0.0002
range = [-5, 42]
percent_errors = false
noise_std = 0.0005

[specification.sensors.ctd.absolute_salinity]
# source_id = "noc-npd-era5/npd-eorca12-era5v1/gn/T1m_4d"
source_id = "rapid_data/2_RAPID36_1d_gridT_RAPID1_202303-202303.nc"
variable_name = "soce_abs"
accuracy = 0.005
resolution = 0.0001
drift_per_month = 0.0003
range = [0, 42]
percent_errors = false
noise_std = 0.0005

[specification.sensors.ctd.pressure]
source_id = ""
variable_name = "pressure"
accuracy = -999.999
resolution = -999.999
drift_per_month = -999.999
range = [-999.999,-999.999]
percent_errors = false
noise_std = -999.999

[specification.sensors.dissolved_gas.dissolved_oxygen]
source_id = "cmems_mod_glo_bgc-bio_anfc_0.25deg_P1D-m"
variable_name = "o2"
accuracy = -999.999
resolution = -999.999
drift_per_month = -999.999
range = [-999.999,-999.999]
percent_errors = false
noise_std = -999.999
