project:
  type: website
  output-dir: ../docs

website:
  title: "MAMMA MIA"
  favicon: mammamia_logo.png
  description: A payload simulator
  page-navigation: true
  back-to-top-navigation: true
  navbar:
    background: '#164166'
    left:
      - text: "Home"
        href: index.qmd
      - text: "Getting Started"
        href: installation.qmd
      - text: "Example Usage"
        href: examples.qmd
      - text: "About"
        href: about.qmd
    right:
      - icon: github
        href: https://github.com/NOC-MDP/MammaMia

  sidebar:
    logo: mammamia_logo.png
    search: true
    style: docked
    background: '#00B5FF'
    contents:
      - text: "Home"
        href: index.qmd
      - text: "Installation"
        href: installation.qmd
      - text: "Usage"
        href: usage.qmd
      - text: "Inventory"
        href: inventory.qmd
      - text: "Structure"
        href: structure.qmd
      - text: "Configuration"
        href: configuration.qmd
      - text: "Examples"
        href: examples.qmd
      - text: "Simulators"
        href: simulators.qmd
      - text: "Future Development"
        href: future_dev.qmd
      - text: "About"
        href: about.qmd
  page-footer: "Copyright 2026 National Oceanography Centre"
  repo-url: https://github.com/NOC-MDP/MammaMia/
  repo-subdir: website
  repo-branch: main
  repo-actions: [edit, issue, source]
format:
  html:
    theme: yeti
    highlight-style: pygments
    ccs: styles.css
    toc: true
    toc-depth: 4
    grid:
      sidebar-width: 150px
callout-appearance: simple



