---
title: "configuration"
---

# Configuring MAMMA MIA

MAMMA MIA uses an internal JSON file to specify its platforms, users can create new platforms by writing their own json file and placing it in the working directory where MAMMA MIA is ran from.

## Adding new platforms

Platforms are specifed in a file called platforms.json. An example file looks like this:

``` json
{
    "platforms": [
            {
                "platform_type": "ARGO",
                "platform_model": "APEX",
                "platform_manufacturer": "Teledyne Webb Research",
                "NEMA_coordinate_conversion": false
            },
            {
                "platform_type": "ARGO",
                "platform_model": "ARVOR",
                "platform_manufacturer": "NKE-INSTRUMENTATION",
                "NEMA_coordinate_conversion": false
            }
    ]
}
```

Here two new platforms are specified, two different models of ARGO floats. Currently there are only 4 fields to specify mostly for meta data purposes, type, model, manufacturer. The final boolean field NEMA_coordinate_conversion specifies if the trajectory coordinates require conversion from NMEA coordinates. This is required if the glider simulator is used as this produces a "raw" file but other sources such as processed NetCDF's may already be converted.

## Adding new sensors

Sensors are specified using a file called sensors.json. In the example below two sensors are specified for one of the new ARGO float platforms defined above. An CTD and a data logger. A platform requires a data logger to be specified otherwise it cannot load a trajectory. At least one sensor is required as otherwise no payload will be simulated. All sensors have the same structure:

-   sensor_model: used for meta data purposes

-   instrument_type: defines instrument type NOTE: this is important as this string is used to find the sensor to add it to the platform.

-   specification: dictionary containing a set of parameters the sensor is observing. (see specification section)

-   platform_compatibility: this is a list of platforms that can use this sensor, this must match an specified platform

NOTE: sensors are organised into different sub lists, e.g. CTD and data_logger. These are for help in reading the file and are not used by MAMMA MIA directly.

``` json
{
    "sensors": {
        "CTD": [
            {
                "sensor_model": "APEX CTD",
                "instrument_type": "CTD",
                "specification": {
                    "INSITU_TEMPERATURE": {
                        "accuracy": 0.001,
                        "resolution": 0.001,
                        "drift_per_month": 0.0002,
                        "range": [-5, 42],
                        "percent_errors": false,
                        "noise_std": 0.0005,
                        "meta_data": "insitu temperature"
                    },
                    "PRACTICAL_SALINITY": {
                        "accuracy": 0.005,
                        "resolution": 0.0001,
                        "drift_per_month": 0.003,
                        "range": [0, 42],
                        "percent_errors": false,
                        "noise_std": 0.0025,
                        "meta_data": "practical salinity"
                    },
                    "PRESSURE": {
                        "accuracy": 0.1,
                        "resolution": 0.002,
                        "drift_per_month": 0.0042,
                        "range": [0, 2000],
                        "percent_errors": true,
                        "noise_std": 0.0005,
                        "meta_data": "pressure"
                    }
                },
                "platform_compatibility": ["APEX"]
            }
        ],
        "data_logger": [
            {
                "sensor_model": "APEX Data logger",
                "instrument_type": "data_logger",
                "specification": {
                    "DEPTH": {
                        "accuracy": -999.999,
                        "resolution": -999.999,
                        "drift_per_month": -999.999,
                        "range": [-999.999, -999.999],
                        "percent_errors": false,
                        "noise_std": -999.999,
                        "meta_data": "glider_depth"
                    },
                    "LATITUDE": {
                        "accuracy": -999.999,
                        "resolution": -999.999,
                        "drift_per_month": -999.999,
                        "range": [-999.999, -999.999],
                        "percent_errors": false,
                        "noise_std": -999.999,
                        "meta_data": "latitude"
                    },
                    "LONGITUDE": {
                        "accuracy": -999.999,
                        "resolution": -999.999,
                        "drift_per_month": -999.999,
                        "range": [-999.999, -999.999],
                        "percent_errors": false,
                        "noise_std": -999.999,
                        "meta_data": "longitude"
                    },
                    "TIME": {
                        "accuracy": -999.999,
                        "resolution": -999.999,
                        "drift_per_month": -999.999,
                        "range": [-999.999, -999.999],
                        "percent_errors": false,
                        "noise_std": -999.999,
                        "meta_data": "time"
                    }
                },
                "platform_compatibility": ["APEX"]
            }
        ]
    }
}
```

### Sensor Specification

The specification field in a sensor defines the parameters that the sensor is observing, it also determines the observation error that will be applied to model data to simulate the observation. These values can be used to replicate existing sensors or to simulate entirely new ones. Or if no sensor error simulation is desired then -999.999 can be used as a null/ignore value.

Each parameter in the sensor specification dictionary contains the following:

-   accuracy: a random value is selected from a uniform distribution of plus/minus this value

-   resolution: values are rounded to this amount

-   drift_per_month: this drift rate is applied for all values with start of timeseries assumed to be freshly calibrated

-   range: values are clipped to this range

-   percent_errors: if true then accuracy, resolution, drift and noise are assumed to be percentage values

-   noise_std: sampled random value from a normal distribution with this standard deviation

-   meta_data:

The process for applying this specification is as follows:

1.  generate accuracy bias values

2.  generate random noise values

3.  calculate drift based on timestep

4.  combine errors by summation and add to timeseries

5.  apply resolution rounding

6.  clip to specified range

## Adding new parameters

Parameters are defined based on their meta data from a vocabulary. There are various collections, MAMMA MIA uses the NERC one here: <https://vocab.nerc.ac.uk>

Below is an example that has been created to use with the ARGO platform defined earlier. This is a DEPTH parameter, other platforms use other DEPTH parameters such as GLIDER_DEPTH. Parameters are the same in that they are organised into sublists, in this case "navigation" but these are just for readability and not used by MAMMA MIA.

Every parameter has the following fields, most of these are for meta data purposes and come from the vocabulary entry, but some are critical to the operation of MAMMA MIA.

-   parameter_id: this is the id used within MAMMA MIA for the parameter

-   identifier: this is the vocabulary reference

-   vocab_url: the URL where the vocabulary used for this parameter is held

-   standard_name: short description of parameter

-   unit of measure: units used for this parameter

-   unit_identifier: vocabulary reference for the specific units

-   parameter_definition: longer and more explicit description for the parameter

-   alternate_sources: If this parameter can be converted from others e.g. pressure from depth, potential_temperature to insitu temperature then they are listed here\*

-   alternate_labels: a different label that the parameter can be known by

-   source_names: names that parameter can be in source files \*\*

``` json
{
    "parameters": {
        "navigation": [
            {
                "parameter_id": "DEPTH",
                "identifier": "SDN:OG1::DEPTH",
                "vocab_url": "https://vocab.nerc.ac.uk/collection/OG1/current/DEPTH/",
                "standard_name": "Depth below sea surface (zero at sea level) of measurement platform",
                "unit_of_measure": "Metres",
                "unit_identifier": "SDN:P06::ULAA",
                "parameter_definition": "Depth below surface of the water body by unknown instrument and correction to zero at sea level using unspecified algorithm.",
                "alternate_sources": [""],
                "alternate_labels": ["DEPTH"],
                "source_names": ["depth"  ,"z"]
            }
        ]
    }
}
```

\* MAMMA MIA needs to know how to convert the parameters for this to work, so only specific conversions are supported. See conversion section

\*\* This is the name of the parameter in any data sources, e.g. potential temperature is often stored as thetao, multiple options can be listed

## Converting Parameters

Some parameters can be converted from one to the other, this often requires other parameters to be present, e.g. temperature conversion also requires depths and salinity. The currently supported conversions are:

-   potential temperature to insitu temperature

-   conservative temperature to insitu temperature

-   absolute salinity to practical salinity

-   depth to pressure
