---
title: "Example MAMMA MIA Campaigns"
---

## Single Slocum glider simulating a mooring mission

Single glider repeat diving at single point (over RAPID Array mooring) for 2 days, note that uses the output from the glider mission builder. See simulators section for more information on creating these inputs

``` python
from mamma_mia import Campaign
from mamma_mia import inventory

# create campaign
campaign = Campaign(name="RAPID array virtual mooring",
                    description="single slocum glider deployment at a RAPID mooring",
                    verbose=True,
                    )
# create platform entity (mutable)
Churchill = inventory.create_platform_entity(entity_name="Churchill",platform_model="Slocum_G2",serial_number="unit_398")

# register sensor to platform
Churchill.register_sensor(sensor_type="CTD")
# register platform to the campaign for use in missions
campaign.register_platform(entity=Churchill)

# # # add mission
campaign.add_mission(mission_name="RAD24_01",
                     title="Churchill with CTD deployment at RAPID array mooring eb1l2n",
                     summary="single glider deployed to perform a virtual mooring flight at the eb1l2n RAPID array.",
                     platform_name="Churchill",
                     trajectory_path="data/RAPID-mooring/rapid-mooring.nc",
                     source_location="CMEMS",
                     mission_time_step=60,
                     apply_obs_error=True)

# build missions (search datasets, download datasets, build interpolators etc)
campaign.build_missions()

# run/fly missions
campaign.run()

# visualise the results
campaign.missions["RAD24_01"].plot_trajectory()
campaign.missions["RAD24_01"].show_payload()

# export to zarr file/store
campaign.export()
```

## Replication of existing glider and ALR deployment

Use real trajectories of the BIOCARBON mission to simulate payloads, they are available from [here](https://platforms.bodc.ac.uk/deployment-catalogue/BIO-Carbon/) download the OG netcdf files for each platform.

``` python
# This script creates an payload emulation of the BIO-Carbon Deployment

from mamma_mia import Campaign
from mamma_mia import inventory

# create campaign
campaign = Campaign(name="BIO-Carbon",
                    description="This campaign involves the deployment of two Autosub Long Range (ALR) and four gliders "
                                "in the Iceland Basin under the Biological Influence on Future Ocean Storage of Carbon "
                                "(BIO-Carbon) programme, funded by a Natural Environment Research Council (NERC) "
                                "Strategic Research Grant. The gliders were deployed May 2024 and the ALRs were deployed"
                                " in June 2024, with the gliders being deployed from and recovered by the RRS Discovery "
                                "(DY180) alongside four Argo floats, and the ALRs being shore launched.",
                    verbose=True
                    )


# create platform entities
# since the trajectory is from processed output, NMEA_conversion should be false as the conversion has already been applied
Nelson = inventory.create_platform_entity(entity_name="Nelson",
                                          platform_model="Slocum_G2",
                                          serial_number="unit_397",
                                          NMEA_conversion=False)
Doombar = inventory.create_platform_entity(entity_name="Doombar",
                                           platform_model="Slocum_G2",
                                           serial_number="unit_405",
                                           NMEA_conversion=False)
Cabot = inventory.create_platform_entity(entity_name="Cabot",
                                         platform_model="Slocum_G2",
                                         serial_number="unit_345",
                                         NMEA_conversion=False)
ALR4 = inventory.create_platform_entity(entity_name="ALR4",
                                        platform_model="ALR_1500",
                                        serial_number="ALR_4")
ALR6 = inventory.create_platform_entity(entity_name="ALR6",
                                        platform_model="ALR_1500",
                                        serial_number="ALR_6")

# register sensors to platform entities
Nelson.register_sensor(sensor_type="CTD")
Nelson.register_sensor(sensor_type="radiometer")
Nelson.register_sensor(sensor_type="dissolved_gas")

Doombar.register_sensor(sensor_type="CTD")
Doombar.register_sensor(sensor_type="radiometer")
Doombar.register_sensor(sensor_type="dissolved_gas")

ALR4.register_sensor(sensor_type="CTD")
ALR4.register_sensor(sensor_type="dissolved_gas")
ALR4.register_sensor(sensor_type="optical_backscatter")

ALR6.register_sensor(sensor_type="CTD")
ALR6.register_sensor(sensor_type="dissolved_gas")
ALR6.register_sensor(sensor_type="optical_backscatter")


Cabot.register_sensor(sensor_type="CTD")
Cabot.register_sensor(sensor_type="radiometer")
Cabot.register_sensor(sensor_type="dissolved_gas")


# register platforms to the campaign for use in missions
campaign.register_platform(entity=Nelson)
campaign.register_platform(entity=Doombar)
campaign.register_platform(entity=Cabot)
campaign.register_platform(entity=ALR4)
campaign.register_platform(entity=ALR6)

# # add Nelson mission
campaign.add_mission(mission_name="Deployment_646",
                     title="Nelson BIO-Carbon deployment",
                     summary="Nelsons's mission that it undertook during BIO-Carbon",
                     platform_name="Nelson",
                     trajectory_path="BioCarbonTrajectories/Nelson_646_R.nc",
                     creator=creator,
                     publisher=publisher,
                     contributor=contributor,
                     source_location="CMEMS",
                     mission_time_step=60)

# # add Doombar mission
campaign.add_mission(mission_name="Deployment_648",
                     title="Doombar BIO-Carbon deployment",
                     summary="Doombar's mission that it undertook during BIO-Carbon",
                     platform_name="Doombar",
                     trajectory_path="BioCarbonTrajectories/Doombar_648_R.nc",
                     creator=creator,
                     publisher=publisher,
                     contributor=contributor,
                     source_location="CMEMS",
                     mission_time_step=60)

# # add ALR4 mission
campaign.add_mission(mission_name="Deployment_649",
                     title="ALR4 BIO-Carbon deployment",
                     summary="ALR4's mission that it undertook during BIO-Carbon",
                     platform_name="ALR4",
                     trajectory_path="BioCarbonTrajectories/ALR_4_649_R.nc",
                     creator=creator,
                     publisher=publisher,
                     contributor=contributor,
                     source_location="CMEMS",
                     mission_time_step=60)

# # add ALR6 mission
campaign.add_mission(mission_name="Deployment_650",
                     title="ALR6 BIO-Carbon deployment",
                     summary="ALR6's mission that it undertook during BIO-Carbon",
                     platform_name="ALR6",
                     trajectory_path="BioCarbonTrajectories/ALR_6_650_R.nc",
                     creator=creator,
                     publisher=publisher,
                     contributor=contributor,
                     source_location="CMEMS",
                     mission_time_step=60)

# # add Cabot mission
campaign.add_mission(mission_name="Deployment_645",
                     title="Cabot BIO-Carbon deployment",
                     summary="Cabot's mission that it undertook during BIO-Carbon",
                     platform_name="Cabot",
                     trajectory_path="BioCarbonTrajectories/Cabot_645_R.nc",
                     creator=creator,
                     publisher=publisher,
                     contributor=contributor,
                     source_location="CMEMS",
                     mission_time_step=60)

# build missions (search datasets, download datasets, build interpolators etc)
campaign.build_missions()

# run/fly missions
campaign.run()

# visualise the results for deployment 650
campaign.missions["Deployment_650"].plot_trajectory()
campaign.missions["Deployment_650"].show_payload(parameter="DISSOLVED_OXYGEN")

# export the campaign
campaign.export()
```

## Way points from CSV file

This reads in waypoints from a csv file containing time/date, latitude, longitude, depth and headings that give the relevant navigation parameter names to use (in this case an ALR1500).

``` csv
TIME,ALATPT01,ALONPT01,ADEPPT01
15/06/2023 00:00:00,72,30,5
16/06/2023 00:01:00,73.5,30,5
17/06/2023 00:02:00,73.75,30,125
18/06/2023 00:03:00,74,30,325
19/06/2023 00:04:00,74.8,30,325
20/06/2023 00:05:00,74.87,30,250
21/06/2023 00:06:00,74.94,30,125
22/06/2023 00:07:00,75,30,5
23/06/2023 00:08:00,75.6,30,5
24/06/2023 00:09:00,75.7,30,50
25/06/2023 00:10:00,75.8,30,100
26/06/2023 00:11:00,76,30,100
27/06/2023 00:12:00,76.1,30,50
28/06/2023 00:13:00,76.2,30,5
29/06/2023 00:14:00,76.4,30,5
30/06/2023 00:15:00,76.5,30,50
01/07/2023 00:16:00,76.6,30,100
02/07/2023 00:17:00,77,30,100
03/07/2023 00:18:00,77.1,30,50
04/07/2023 00:19:00,77.2,30,5
05/07/2023 00:20:00,78,30,5
06/07/2023 00:21:00,78.07,30,75
07/07/2023 00:22:00,78.14,30,175
08/07/2023 00:23:00,78.2,30,225
09/07/2023 00:24:00,78.6,30,225
10/07/2023 00:25:00,78.67,30,175
11/07/2023 00:26:00,78.74,30,75
12/07/2023 00:27:00,78.8,30,5
13/07/2023 00:28:00,79.2,30,5
14/07/2023 00:29:00,79.6,30,125
```

When used as a trajectory input, MAMMAMIA will take these points and linearly interpolate between them based on the requested mission timestep. The snippet below shows an example.

``` python
from mamma_mia import Campaign
from mamma_mia import inventory

campaign = Campaign(name="ALR arctic visualisation",
                    description="single ALR capability demo in the arctic",
                    verbose=True
                    )

ALR4 = inventory.create_platform_entity(entity_name="ALR4",
                                        platform="ALR_1500",
                                        serial_number="ALR_4")

ALR4.register_sensor(sensor_type="CTD")

campaign.register_platform(entity=ALR4)

# # add ALR4 mission
campaign.add_mission(mission_name="Arctic Visualisation",
                     title="Under Ice capability demo",
                     summary="",
                     platform_name="ALR4",
                     trajectory_path="arctic_vis_traj.csv",
                     source_location="MSM",
                     mission_time_step=60)

# build missions (search datasets, download datasets, build interpolators etc)
campaign.build_missions()

# run/fly missions
campaign.run()
campaign.missions["Arctic Visualisation"].plot_trajectory()
campaign.missions["Arctic Visualisation"].show_payload()
campaign.export()

campaign.missions["Arctic Visualisation"].export_payload("output2.csv")
```

## Example simulated ALR mission

To be updated
