---
title: "Future Development"
---

This page details the future development plans for the MAMMA MIA python module.

## Support for Airborne Platforms

Currently only subsurface platforms are supported, MAMMA MIA also does not simulate payloads at the surface (approx less than 0.5 m) due to needing to switch to a different data product at this point (from a 3D to a surface field). Future work will make this seamless and also introduce the option of simulating the payloads of airborne platforms, and introducing new observation types such as swaths.

## Support for Lagrangian Drifters (e.g. ARGO floats)

MAMMA MIA currently doesn't support a typical Lagrangian python library output (PARCELS), this is due to the fact that PARCELS output does not have a time dimension but is an effectively a 2D array of observations and drifters. This support will be implemented so an ARGO simulator can be integrated into MAMMA MIA.

## Support for Xarray

MAMMA MIA uses the zarr library directly to export its campaign objects. In hindsight this is less than ideal as it is not currently compatible with Xarray due to missing dim meta data and the fact that xarray datasets cannot handle a zarr group hierarchy.

Xarray datatrees look like a good solution, using this as the export format means that it will be compatible with Xarray and also still able to optionally export as a zarr file for backwards compatibility.
